---
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependencies:
  - role: creategroup
    _name: chartrepo
    _gid: "{{ caas.uid.chartrepo }}"
    become: true
    become_user: "root"

  - role: createuser
    _name: chartrepo
    _group: chartrepo
    _groups: ''
    _shell: /sbin/nologin
    _home: /
    _uid: "{{ caas.uid.chartrepo }}"
    become: true
    become_user: "root"

  - role: cert
    instance: "chart-repo{{ nodeindex }}"
    cert_path: /etc/chart-repo/ssl
    add_users:
      - chartrepo
    alt_names:
      dns:
        - "{{ caas.chart_repo_url }}"
    become: true
    become_user: "root"

  - role: docker_image_load
    images:
      - chartrepo

  - role: docker_image_push
    images:
      - chartrepo
    when: nodename | search("caas_master1")

  - role: manifests
